// lib/config/firebase_config.dart
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

class FirebaseConfig {
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }
}

// This file should be generated by FlutterFire CLI:
// flutterfire configure --project=dealhunter-egypt-70d29

// For now, create firebase_options.dart manually:
/*
File: lib/config/firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for macos.');
      case TargetPlatform.windows:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for windows.');
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM7irklt9VLM7NrIXovI3oZQ9wkoodywU',
    appId: '1:477835366168:web:YOUR_WEB_APP_ID',
    messagingSenderId: '477835366168',
    projectId: 'dealhunter-egypt-70d29',
    authDomain: 'dealhunter-egypt-70d29.firebaseapp.com',
    storageBucket: 'dealhunter-egypt-70d29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YOUR-ANDROID-API-KEY',
    appId: '1:477835366168:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '477835366168',
    projectId: 'dealhunter-egypt-70d29',
    storageBucket: 'dealhunter-egypt-70d29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-YOUR-iOS-API-KEY',
    appId: '1:477835366168:ios:YOUR_iOS_APP_ID',
    messagingSenderId: '477835366168',
    projectId: 'dealhunter-egypt-70d29',
    storageBucket: 'dealhunter-egypt-70d29.appspot.com',
    iosBundleId: 'com.dealhunter.admin',
  );
}
*/
