steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.scraper', '-t', 'gcr.io/dealhunter-egypt-70d29/dealhunter-scraper:latest', '.']
images:
- 'gcr.io/dealhunter-egypt-70d29/dealhunter-scraper:latest'
