import { getDb } from "../api/queries/connection";
import { platforms, categories, deals } from "./schema";

async function seed() {
  const db = getDb();

  console.log("Seeding platforms...");
  await db.insert(platforms).values([
    {
      name: "Amazon Egypt",
      code: "amazon-eg",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
      baseUrl: "https://www.amazon.eg",
      color: "#FF9900",
    },
    {
      name: "Noon Egypt",
      code: "noon-eg",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Noon_com_logo.svg",
      baseUrl: "https://www.noon.com/egypt-en",
      color: "#FFD700",
    },
    {
      name: "Jumia Egypt",
      code: "jumia-eg",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/62/Jumia_logo.svg",
      baseUrl: "https://www.jumia.com.eg",
      color: "#F68B1E",
    },
  ]);

  console.log("Seeding categories...");
  await db.insert(categories).values([
    { name: "Electronics", slug: "electronics", icon: "Smartphone", displayOrder: 1 },
    { name: "Fashion", slug: "fashion", icon: "Shirt", displayOrder: 2 },
    { name: "Home & Kitchen", slug: "home-kitchen", icon: "Home", displayOrder: 3 },
    { name: "Beauty & Personal Care", slug: "beauty", icon: "Sparkles", displayOrder: 4 },
    { name: "Mobile Phones", slug: "mobile-phones", icon: "Phone", displayOrder: 5 },
    { name: "Appliances", slug: "appliances", icon: "Tv", displayOrder: 6 },
    { name: "Toys & Games", slug: "toys-games", icon: "Gamepad2", displayOrder: 7 },
    { name: "Sports & Fitness", slug: "sports-fitness", icon: "Dumbbell", displayOrder: 8 },
    { name: "Supermarket", slug: "supermarket", icon: "ShoppingCart", displayOrder: 9 },
    { name: "Health", slug: "health", icon: "Heart", displayOrder: 10 },
    { name: "Books & Stationery", slug: "books", icon: "BookOpen", displayOrder: 11 },
    { name: "Automotive", slug: "automotive", icon: "Car", displayOrder: 12 },
  ]);

  console.log("Seeding deals...");
  const dealData = [
    // Amazon Egypt - Electronics (40%+ discounts)
    {
      platformId: 1,
      categoryId: 1,
      title: "Samsung Galaxy A15 6GB RAM, 128GB - Blue Black",
      description: "6.5\" Super AMOLED display, 50MP triple camera, 5000mAh battery",
      productUrl: "https://www.amazon.eg/Samsung-Galaxy-128GB-Blue-Black/dp/B0CNVXYLND",
      imageUrl: "https://images.unsplash.com/photo-1610945265078-3858a0b5d837?w=400&h=400&fit=crop",
      originalPrice: "6999.00",
      salePrice: "4199.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 1,
      categoryId: 1,
      title: "Xiaomi Redmi Note 13 8GB RAM, 256GB - Midnight Black",
      description: "120Hz AMOLED, 108MP camera, 5000mAh with 33W fast charging",
      productUrl: "https://www.amazon.eg/Xiaomi-Redmi-Note-13-256GB/dp/B0CSP8WXY1",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop",
      originalPrice: "10999.00",
      salePrice: "5499.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 1,
      categoryId: 1,
      title: "Apple AirPods Pro 2nd Gen with USB-C",
      description: "Active Noise Cancellation, Adaptive Audio, Personalized Spatial Audio",
      productUrl: "https://www.amazon.eg/Apple-AirPods-Pro-2nd-Generation/dp/B0CHWRXH8B",
      imageUrl: "https://images.unsplash.com/photo-1603351154351-5cfb3d04ef32?w=400&h=400&fit=crop",
      originalPrice: "13999.00",
      salePrice: "7999.00",
      discountPercent: 43,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 1,
      categoryId: 1,
      title: "Samsung 55\" Crystal UHD 4K Smart TV (2024 Model)",
      description: "PurColor, Crystal Processor 4K, Smart Hub, HDR10+",
      productUrl: "https://www.amazon.eg/Samsung-Crystal-UHD-Smart-2024/dp/B0CZPDZ2JX",
      imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop",
      originalPrice: "24999.00",
      salePrice: "14999.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 1,
      categoryId: 1,
      title: "Soundcore Life Q30 Hybrid Active Noise Cancelling Headphones",
      description: "Hi-Res Audio, 40-hour playtime, comfortable over-ear design",
      productUrl: "https://www.amazon.eg/Soundcore-Cancelling-Headphones-Comfortable-Bluetooth/dp/B08HMWZBXC",
      imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
      originalPrice: "4999.00",
      salePrice: "2499.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    // Amazon Egypt - Fashion (40-80% off)
    {
      platformId: 1,
      categoryId: 2,
      title: "Nike Men's Revolution 6 Running Shoes - Black/White",
      description: "Breathable mesh upper, foam midsole, rubber outsole",
      productUrl: "https://www.amazon.eg/Nike-Revolution-Running-Shoes-Black/dp/B09PBN4W3G",
      imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
      originalPrice: "5499.00",
      salePrice: "2199.00",
      discountPercent: 60,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 1,
      categoryId: 2,
      title: "Adidas Women's Essentials Logo Fleece Hoodie",
      description: "Cotton-blend fleece, kangaroo pocket, regular fit",
      productUrl: "https://www.amazon.eg/Adidas-Womens-Essentials-Logo-Fleece/dp/B08P4GRYYX",
      imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=400&fit=crop",
      originalPrice: "4299.00",
      salePrice: "1289.00",
      discountPercent: 70,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 1,
      categoryId: 2,
      title: "Skechers Men's Summits Trainers - Navy",
      description: "Air-cooled memory foam, lightweight mesh upper",
      productUrl: "https://www.amazon.eg/Skechers-Summits-Trainers-Navy/dp/B07PYVVVS2",
      imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=400&fit=crop",
      originalPrice: "3999.00",
      salePrice: "1999.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 1,
      categoryId: 2,
      title: "Casio Men's Digital Watch F-91W-1 - Classic Black",
      description: "Daily alarm, chronograph, LED light, water resistant",
      productUrl: "https://www.amazon.eg/Casio-Digital-Watch-F-91W-1/dp/B000J3NVBK",
      imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop",
      originalPrice: "899.00",
      salePrice: "449.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    // Amazon Egypt - Home & Kitchen (40%+)
    {
      platformId: 1,
      categoryId: 3,
      title: "Philips Essential Air Fryer HD9200/90 - 4.1L",
      description: "Rapid Air technology, touch screen, 7 presets, dishwasher safe",
      productUrl: "https://www.amazon.eg/Philips-Essential-Airfryer- touch-screen/dp/B08J4FZQ7P",
      imageUrl: "https://images.unsplash.com/photo-1626147116986-4601771470a6?w=400&h=400&fit=crop",
      originalPrice: "8999.00",
      salePrice: "4499.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 1,
      categoryId: 3,
      title: "Kenwood 3-in-1 Blender with Grinder & Chopper - 500W",
      description: "1.5L jug, stainless steel blades, 2 speeds + pulse",
      productUrl: "https://www.amazon.eg/Kenwood-Blender-Grinder-Chopper-500W/dp/B07D4QZZCH",
      imageUrl: "https://images.unsplash.com/photo-1570222094114-28a9d88a66d4?w=400&h=400&fit=crop",
      originalPrice: "3499.00",
      salePrice: "1749.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 1,
      categoryId: 3,
      title: "Tornado Automatic Turkish Coffee Maker - 330ml",
      description: "One-touch operation, boil-dry protection, stainless steel",
      productUrl: "https://www.amazon.eg/Tornado-Automatic-Turkish-Coffee-330ml/dp/B08WXYZ123",
      imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=400&h=400&fit=crop",
      originalPrice: "2999.00",
      salePrice: "1499.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    // Amazon Egypt - Beauty (40%+)
    {
      platformId: 1,
      categoryId: 4,
      title: "La Roche-Posay Cicaplast B5 Repairing Balm - 100ml",
      description: "Soothing multi-purpose cream for dry, irritated skin",
      productUrl: "https://www.amazon.eg/La-Roche-Posay-Cicaplast-Repairing-Balm/dp/B002D48QUC",
      imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
      originalPrice: "899.00",
      salePrice: "539.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 1,
      categoryId: 4,
      title: "L'Oreal Paris Revitalift Laser X3 Anti-Aging Day Cream",
      description: "Pro-Xylane, hyaluronic acid, reduces wrinkles",
      productUrl: "https://www.amazon.eg/LOreal-Paris-Revitalift-Laser-Anti-Aging/dp/B00DLSX8FQ",
      imageUrl: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop",
      originalPrice: "549.00",
      salePrice: "329.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 1,
      categoryId: 4,
      title: "Braun Series 3 ProSkin Electric Shaver 3000s",
      description: "3 pressure-sensitive shaving elements, rechargeable, wet & dry",
      productUrl: "https://www.amazon.eg/Braun-Series-ProSkin-Electric-Shaver/dp/B01M9I779K",
      imageUrl: "https://images.unsplash.com/photo-1621607512022-6aecc4fed814?w=400&h=400&fit=crop",
      originalPrice: "3999.00",
      salePrice: "1999.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    // Amazon Egypt - Appliances
    {
      platformId: 1,
      categoryId: 6,
      title: "Tornado Automatic Washing Machine 7kg - White",
      description: "Top load, 1200 RPM, 8 programs, energy efficient",
      productUrl: "https://www.amazon.eg/Tornado-Automatic-Washing-Machine-7kg/dp/B0ABC12345",
      imageUrl: "https://images.unsplash.com/photo-1626806775351-538068a21838?w=400&h=400&fit=crop",
      originalPrice: "12999.00",
      salePrice: "7799.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 1,
      categoryId: 6,
      title: "Kiriazi Refrigerator 14 Feet - Digital No Frost",
      description: "No frost technology, digital display, inverter compressor",
      productUrl: "https://www.amazon.eg/Kiriazi-Refrigerator-Digital-Frost/dp/B0DEF12345",
      imageUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=400&fit=crop",
      originalPrice: "42999.00",
      salePrice: "30099.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: true,
    },
    // Noon Egypt - Electronics
    {
      platformId: 2,
      categoryId: 5,
      title: "iPhone 15 128GB - Pink",
      description: "A16 Bionic chip, 48MP main camera, USB-C, Dynamic Island",
      productUrl: "https://www.noon.com/egypt-en/iphone-15-128gb-pink/N53439147A/p",
      imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop",
      originalPrice: "59999.00",
      salePrice: "44999.00",
      discountPercent: 25,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 2,
      categoryId: 1,
      title: "Samsung Galaxy S24 Ultra 256GB - Titanium Gray",
      description: "6.8\" QHD+ AMOLED, 200MP camera, S Pen, AI features",
      productUrl: "https://www.noon.com/egypt-en/samsung-galaxy-s24-ultra-256gb/N53456789A/p",
      imageUrl: "https://images.unsplash.com/photo-1707229723375-7845320c7340?w=400&h=400&fit=crop",
      originalPrice: "74999.00",
      salePrice: "52499.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 2,
      categoryId: 1,
      title: "Infinix Hot 40 Pro 8GB RAM, 256GB - Horizon Gold",
      description: "120Hz display, 108MP camera, 5000mAh battery",
      productUrl: "https://www.noon.com/egypt-en/infinix-hot-40-pro-256gb/N53456790A/p",
      imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&h=400&fit=crop",
      originalPrice: "8999.00",
      salePrice: "6299.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 2,
      categoryId: 1,
      title: "Apple Watch Series 9 GPS 45mm - Midnight Aluminum",
      description: "S9 SiP, Retina display, health sensors, water resistant",
      productUrl: "https://www.noon.com/egypt-en/apple-watch-series-9-45mm/N53456791A/p",
      imageUrl: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400&h=400&fit=crop",
      originalPrice: "28999.00",
      salePrice: "21749.00",
      discountPercent: 25,
      currency: "EGP",
      isFeatured: true,
    },
    // Noon Egypt - Fashion
    {
      platformId: 2,
      categoryId: 2,
      title: "Adidas Ultraboost Light Running Shoes - Core Black",
      description: "Light BOOST midsole, Primeknit upper, Continental rubber outsole",
      productUrl: "https://www.noon.com/egypt-en/adidas-ultraboost-light/N53456792A/p",
      imageUrl: "https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=400&h=400&fit=crop",
      originalPrice: "8999.00",
      salePrice: "4499.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 2,
      categoryId: 2,
      title: "Nike Air Force 1 '07 - White",
      description: "Leather upper, Air sole unit, classic low-top design",
      productUrl: "https://www.noon.com/egypt-en/nike-air-force-1-white/N53456793A/p",
      imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop",
      originalPrice: "6499.00",
      salePrice: "4549.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 2,
      categoryId: 2,
      title: "Citizen Eco-Drive Promaster Diver Watch - Blue",
      description: "Solar powered, 200m water resistant, stainless steel",
      productUrl: "https://www.noon.com/egypt-en/citizen-eco-drive-promaster/N53456794A/p",
      imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop",
      originalPrice: "14999.00",
      salePrice: "5999.00",
      discountPercent: 60,
      currency: "EGP",
      isFeatured: true,
    },
    // Noon Egypt - Home & Kitchen
    {
      platformId: 2,
      categoryId: 3,
      title: "Essential XI Air Fryer 5.5L Digital - Black",
      description: "Touch control, 7 presets, 1700W, non-stick basket",
      productUrl: "https://www.noon.com/egypt-en/essential-xi-air-fryer-5-5l/N53456795A/p",
      imageUrl: "https://images.unsplash.com/photo-1626147116986-4601771470a6?w=400&h=400&fit=crop",
      originalPrice: "5499.00",
      salePrice: "2749.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 2,
      categoryId: 3,
      title: "Tefal Easy Fry Precision XXL 4.2L Air Fryer",
      description: "8 presets, digital timer, dishwasher safe parts",
      productUrl: "https://www.noon.com/egypt-en/tefal-easy-fry-precision/N53456796A/p",
      imageUrl: "https://images.unsplash.com/photo-1626147116986-4601771470a6?w=400&h=400&fit=crop",
      originalPrice: "7999.00",
      salePrice: "3999.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 2,
      categoryId: 3,
      title: "Kenwood kMix Stand Mixer - 5L, Cream",
      description: "1000W motor, 3 attachments, planetary mixing action",
      productUrl: "https://www.noon.com/egypt-en/kenwood-kmix-stand-mixer/N53456797A/p",
      imageUrl: "https://images.unsplash.com/photo-1570222094114-0d88a66d4c03?w=400&h=400&fit=crop",
      originalPrice: "18999.00",
      salePrice: "11399.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    // Noon Egypt - Beauty
    {
      platformId: 2,
      categoryId: 4,
      title: "Dior Sauvage Eau de Parfum 100ml",
      description: "Calabrian bergamot, vanilla, amber wood",
      productUrl: "https://www.noon.com/egypt-en/dior-sauvage-edp-100ml/N53456798A/p",
      imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop",
      originalPrice: "8999.00",
      salePrice: "6299.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 2,
      categoryId: 4,
      title: "The Ordinary Niacinamide 10% + Zinc 1% - 30ml",
      description: "Brightening serum, reduces blemishes, oil control",
      productUrl: "https://www.noon.com/egypt-en/the-ordinary-niacinamide/N53456799A/p",
      imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
      originalPrice: "499.00",
      salePrice: "299.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 2,
      categoryId: 4,
      title: "Lancôme La Vie Est Belle EDP 75ml",
      description: "Iris, patchouli, vanilla, spun sugar accord",
      productUrl: "https://www.noon.com/egypt-en/lancome-la-vie-est-belle-75ml/N53456800A/p",
      imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop",
      originalPrice: "7499.00",
      salePrice: "3749.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    // Noon Egypt - Toys
    {
      platformId: 2,
      categoryId: 7,
      title: "LEGO Creator 3-in-1 Space Shuttle Adventure 31134",
      description: "486 pieces, ages 6+, 3 build options",
      productUrl: "https://www.noon.com/egypt-en/lego-creator-space-shuttle/N53456801A/p",
      imageUrl: "https://images.unsplash.com/photo-1585366119957-f973043d4561?w=400&h=400&fit=crop",
      originalPrice: "2499.00",
      salePrice: "1499.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    // Jumia Egypt - Mobile Phones
    {
      platformId: 3,
      categoryId: 5,
      title: "Tecno Spark 20 Pro 8GB RAM, 256GB - Temporal Orbits",
      description: "6.78\" 120Hz display, 108MP camera, 5000mAh battery",
      productUrl: "https://www.jumia.com.eg/tecno-spark-20-pro-256gb",
      imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
      originalPrice: "8499.00",
      salePrice: "5949.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 3,
      categoryId: 5,
      title: "Realme C67 8GB RAM, 128GB - Sunny Oasis",
      description: "6.72\" 90Hz display, 108MP camera, 5000mAh with 33W charging",
      productUrl: "https://www.jumia.com.eg/realme-c67-128gb",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop",
      originalPrice: "7499.00",
      salePrice: "5249.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 3,
      categoryId: 1,
      title: "Honor X9b 12GB RAM, 256GB - Sunrise Orange",
      description: "120Hz AMOLED, 108MP triple camera, 5800mAh battery",
      productUrl: "https://www.jumia.com.eg/honor-x9b-256gb",
      imageUrl: "https://images.unsplash.com/photo-1592899677879-a4bb92f829d1?w=400&h=400&fit=crop",
      originalPrice: "17999.00",
      salePrice: "12599.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 3,
      categoryId: 1,
      title: "Samsung Galaxy Tab A9+ 11\" 128GB WiFi - Silver",
      description: "90Hz display, Snapdragon 695, 7040mAh battery",
      productUrl: "https://www.jumia.com.eg/samsung-galaxy-tab-a9-plus",
      imageUrl: "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=400&h=400&fit=crop",
      originalPrice: "12999.00",
      salePrice: "9099.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: false,
    },
    // Jumia Egypt - Fashion
    {
      platformId: 3,
      categoryId: 2,
      title: "Puma Smash v2 Leather Sneakers - White/Navy",
      description: "SoftFoam+ sockliner, leather upper, rubber outsole",
      productUrl: "https://www.jumia.com.eg/puma-smash-v2-sneakers",
      imageUrl: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=400&h=400&fit=crop",
      originalPrice: "4999.00",
      salePrice: "2499.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 3,
      categoryId: 2,
      title: "LC Waikiki Men's Slim Fit Chino Pants - Navy",
      description: "Cotton blend, slim fit, 4-pocket design",
      productUrl: "https://www.jumia.com.eg/lc-waikiki-mens-chino-pants",
      imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=400&fit=crop",
      originalPrice: "1299.00",
      salePrice: "649.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 3,
      categoryId: 2,
      title: "DeFacto Women's Crossbody Bag - Black",
      description: "Faux leather, adjustable strap, zip closure",
      productUrl: "https://www.jumia.com.eg/defacto-womens-crossbody-bag",
      imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop",
      originalPrice: "1599.00",
      salePrice: "799.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    // Jumia Egypt - Home & Kitchen
    {
      platformId: 3,
      categoryId: 3,
      title: "Tornado Stand Mixer 5L - 1000W, Silver",
      description: "5 speed settings, 3 attachments, planetary mixing",
      productUrl: "https://www.jumia.com.eg/tornado-stand-mixer-5l",
      imageUrl: "https://images.unsplash.com/photo-1570222094114-0d88a66d4c03?w=400&h=400&fit=crop",
      originalPrice: "5499.00",
      salePrice: "3299.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 3,
      categoryId: 3,
      title: "Fresh Electric Kettle 1.7L - 2200W, Stainless Steel",
      description: "Boil-dry protection, auto shut-off, LED indicator",
      productUrl: "https://www.jumia.com.eg/fresh-electric-kettle-1-7l",
      imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=400&h=400&fit=crop",
      originalPrice: "1299.00",
      salePrice: "649.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    // Jumia Egypt - Beauty
    {
      platformId: 3,
      categoryId: 4,
      title: "Garnier Micellar Cleansing Water 400ml - Pink",
      description: "All-in-1 cleanser, removes makeup, no rinsing",
      productUrl: "https://www.jumia.com.eg/garnier-micellar-water-400ml",
      imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
      originalPrice: "349.00",
      salePrice: "209.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 3,
      categoryId: 4,
      title: "L'Oreal Paris Elvive Hyaluron Plump Shampoo 400ml",
      description: "Hyaluronic acid filler, hydrates dry hair",
      productUrl: "https://www.jumia.com.eg/loreal-elvive-hyaluron-shampoo",
      imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop",
      originalPrice: "249.00",
      salePrice: "149.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 3,
      categoryId: 4,
      title: "Hugo Boss Bottled EDT 100ml",
      description: "Apple, cinnamon, sandalwood, vetiver",
      productUrl: "https://www.jumia.com.eg/hugo-boss-bottled-edt-100ml",
      imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop",
      originalPrice: "5999.00",
      salePrice: "2999.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    // Jumia Egypt - Sports
    {
      platformId: 3,
      categoryId: 8,
      title: "Spokey Yoga Mat 6mm - Purple",
      description: "Non-slip, PVC foam, carry strap included",
      productUrl: "https://www.jumia.com.eg/spokey-yoga-mat-6mm",
      imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
      originalPrice: "899.00",
      salePrice: "449.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: false,
    },
    // Jumia Egypt - Appliances
    {
      platformId: 3,
      categoryId: 6,
      title: "Fresh Air Conditioner 1.5 HP - Inverter, White",
      description: "Cold only, energy saving inverter, Turbo mode",
      productUrl: "https://www.jumia.com.eg/fresh-air-conditioner-1-5-hp",
      imageUrl: "https://images.unsplash.com/photo-1631545308772-81a0e0a3a6ae?w=400&h=400&fit=crop",
      originalPrice: "24999.00",
      salePrice: "19999.00",
      discountPercent: 20,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 3,
      categoryId: 6,
      title: "Toshiba Vacuum Cleaner 2000W - Red/Black",
      description: "Bagless, HEPA filter, 2L dust capacity",
      productUrl: "https://www.jumia.com.eg/toshiba-vacuum-cleaner-2000w",
      imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=400&fit=crop",
      originalPrice: "4499.00",
      salePrice: "3149.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: false,
    },
    // Additional Amazon deals
    {
      platformId: 1,
      categoryId: 4,
      title: "Nivea Soft Moisturizing Cream 300ml - Pack of 2",
      description: "Vitamin E, jojoba oil, for face, hands, body",
      productUrl: "https://www.amazon.eg/Nivea-Soft-Moisturizing-Cream-300ml/dp/B0ABC45678",
      imageUrl: "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?w=400&h=400&fit=crop",
      originalPrice: "399.00",
      salePrice: "239.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 1,
      categoryId: 7,
      title: "Monopoly Classic Board Game",
      description: "For ages 8+, 2-6 players, classic property trading game",
      productUrl: "https://www.amazon.eg/Monopoly-Classic-Board-Game/dp/B0ABC45679",
      imageUrl: "https://images.unsplash.com/photo-1610890716171-6b1c9f2bd40c?w=400&h=400&fit=crop",
      originalPrice: "1299.00",
      salePrice: "779.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    // Additional Noon deals
    {
      platformId: 2,
      categoryId: 1,
      title: "JBL Tune 760NC Wireless Noise Cancelling Headphones",
      description: "Active noise cancelling, 35h battery, pure bass sound",
      productUrl: "https://www.noon.com/egypt-en/jbl-tune-760nc/N53456802A/p",
      imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
      originalPrice: "5499.00",
      salePrice: "2749.00",
      discountPercent: 50,
      currency: "EGP",
      isFeatured: true,
    },
    {
      platformId: 2,
      categoryId: 3,
      title: "Dyson V12 Detect Slim Fluffy Vacuum Cleaner",
      description: "Laser detect technology, 60 min runtime, HEPA filtration",
      productUrl: "https://www.noon.com/egypt-en/dyson-v12-detect-slim/N53456803A/p",
      imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=400&fit=crop",
      originalPrice: "44999.00",
      salePrice: "35999.00",
      discountPercent: 20,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 2,
      categoryId: 2,
      title: "Ray-Ban Aviator Classic RB3025 - Gold/Green",
      description: "Iconic aviator shape, crystal glass lenses, UV protection",
      productUrl: "https://www.noon.com/egypt-en/ray-ban-aviator-classic/N53456804A/p",
      imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop",
      originalPrice: "8999.00",
      salePrice: "6299.00",
      discountPercent: 30,
      currency: "EGP",
      isFeatured: false,
    },
    // Additional Jumia deals
    {
      platformId: 3,
      categoryId: 9,
      title: "Always Platinum Sanitary Pads Size 2 - 30 Pack",
      description: "Secure gel technology, odor lock, soft wings",
      productUrl: "https://www.jumia.com.eg/always-platinum-size-2-30-pack",
      imageUrl: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400&h=400&fit=crop",
      originalPrice: "299.00",
      salePrice: "179.00",
      discountPercent: 40,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 3,
      categoryId: 9,
      title: "Nestlé Nido Fortified Milk Powder 2.25kg",
      description: "Full cream, fortified with vitamins and minerals",
      productUrl: "https://www.jumia.com.eg/nestle-nido-milk-powder-2-25kg",
      imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop",
      originalPrice: "899.00",
      salePrice: "719.00",
      discountPercent: 20,
      currency: "EGP",
      isFeatured: false,
    },
    {
      platformId: 3,
      categoryId: 5,
      title: "Xiaomi Redmi 13C 8GB RAM, 256GB - Midnight Black",
      description: "6.74\" 90Hz display, 50MP camera, 5000mAh battery",
      productUrl: "https://www.jumia.com.eg/xiaomi-redmi-13c-256gb",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop",
      originalPrice: "6999.00",
      salePrice: "5599.00",
      discountPercent: 20,
      currency: "EGP",
      isFeatured: false,
    },
  ];

  console.log(`Seeding ${dealData.length} deals...`);
  for (const deal of dealData) {
    await db.insert(deals).values(deal);
  }

  console.log("Seed complete!");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
